### ISSUE TITLE
baldengineer/bit-preserve

### ISSUE THREAD

**Issue by mrand** [sporniket/retro-computer-clean-schematics#52]
Very neat!  

Might I suggest a PR into https://github.com/baldengineer/bit-preserve?

**Comment by sporniket** [comment]
Hello, sorry for the late reply.

I would suggest that you add a git submodule in the Atari folder, linked to
https://github.com/sporniket/kicad-conversions--atari-ste-motherboard--c300780-001
The repository in itself is quite heavy, as there is also very heavy
reference pictures of the original motherboard that I have, so I do not
recommend to make a copy into yours.

Alternatively, just grab the released standalone Kicad project that you
will find here :
https://github.com/sporniket/kicad-conversions--atari-ste-motherboard--c300780-001/releases/tag/1.0.0

Best regards.

Le dim. 5 sept. 2021 à 17:08, Marc Randolph ***@***.***> a
écrit :
